# Generated by Django 2.2 on 2020-01-07 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_auto_20200108_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingProdile',
            new_name='BillingProfile',
        ),
    ]
