# Generated by Django 2.2 on 2020-01-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='brand',
            new_name='outcome_type',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='country',
            new_name='risk_level',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='default',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='last4',
        ),
        migrations.AddField(
            model_name='charge',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='seller_message',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
