# Generated by Django 2.2 on 2020-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200122_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
